#ifndef HTTPSTATUS_HPP
#define HTTPSTATUS_HPP

namespace HttpStatus
{
	enum Code
	{
		OK = 200,
		CREATED = 201,
		NO_CONTENT = 204,
		MOVED_PERMANENTLY = 301,
		FOUND = 302,
		BAD_REQUEST = 400,
		FORBIDDEN = 403,
		NOT_FOUND = 404,
		METHOD_NOT_ALLOWED = 405,
		REQUEST_TIMEOUT = 408,
		LENGTH_REQUIRED = 411,
		PAYLOAD_TOO_LARGE = 413,
		REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
		INTERNAL_SERVER_ERROR = 500,
		NOT_IMPLEMENTED = 501,
		HTTP_VERSION_NOT_SUPPORTED = 505
	};
}

#endif
